### ISSUE TITLE
llvmlite 0.42.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#1022]
## llvmlite 0.42.0

* [x] Merge to `main`.
    * nothing new
* [x] Create 0.42 release branch `release0.42`
    * [ ] Update `CHANGE_LOG` in a PR targeting the release branch.
    * [ ] Follow the format of previous `CHANGE_LOG` entries.
* [x] Get the change-log-PR reviewed and merged.
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
    * [x] conda package build and test. `llvmlite_269`
    * [x] wheel build. `llvmlite_wheel_57`
* [x] Annotated tag `v0.42.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). `llvmlite_270`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `llvmlite_wheel_58`
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`.
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Initialize and verify ReadTheDocs build.
* [x] Send RC announcement email / post announcement to discourse group.
* [ ] Post link to X and Mastodon and anywhere else that is appropriate.

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Tag `0.43.0dev0` to start new development cycle on `main`.
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Close milestone (and then close this release issue).
