### ISSUE TITLE
llvmlite 0.42.0 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#1028]
## llvmlite 0.42.0

* [x] ~Cherry-pick items from the 0.42.0 milestone into a PR targeting the release branch.~ N/A, no changes required.
* [x] Update `CHANGE_LOG` on cherry-pick-PR (#1029).
* [x] ~Have cherry-pick-PR reviewed and merged.~ none
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
  * [x] conda package build and test.
  * [x] wheel build.
* [x] Annotated tag `v0.42.0` on release branch (`llvmlite` tags DO have a `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload"). `llvmlite_272`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `llvmlite_wheel_60`
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`.
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter and Mastodon and anywhere else that is appropriate.

### Post release

* [x] Cherry-pick changes to the `CHANGE_LOG` to `main`. (FINAL ONLY) https://github.com/numba/llvmlite/pull/1032
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).
