### ISSUE TITLE
llvmlite 0.43.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#1041]
## llvmlite 0.43.0rc1

* [x] Merge to `main`.
    * [x] `None`
* [x] Create 0.43 release branch `release0.43` https://github.com/numba/llvmlite/tree/release0.43
    * [x] Update `CHANGE_LOG` in a PR targeting the release branch.
      * [x] https://github.com/numba/llvmlite/pull/1047
    * [x] Follow the format of previous `CHANGE_LOG` entries.
* [x] Get the change-log-PR reviewed and merged.
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
    * [x] conda package build and test. <strike>`llvmlite_280`</strike> `llvmlite_281`
    * [x] wheel build. <strike>` llvmlite_wheel_63`</strike> ` llvmlite_wheel_64 `
* [x] Annotated tag `v0.43.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix). https://github.com/numba/llvmlite/releases/tag/v0.43.0rc1
* [x] Build and upload conda packages on buildfarm (check "upload"). `llvmlite_282`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `llvmlite_wheel_66`
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`. https://anaconda.org/numba/llvmlite/files?sort=basename&sort_order=desc&version=0.43.0rc1
* [x] Upload wheels and sdist to PyPI. (upload from ci_artifacts). 
* [x] Verify wheels for all platforms arrived on PyPi. https://pypi.org/project/llvmlite/0.43.0rc1/
* [x] Initialize and verify ReadTheDocs build. https://llvmlite.readthedocs.io/en/v0.43.0rc1/release-notes.html
* [x] Send RC announcement email / post announcement to discourse group. https://numba.discourse.group/t/ann-numba-0-60-0rc1-llvmlite-0-43-0rc1/2565
* [x] Post link to X and Mastodon and anywhere else that is appropriate. https://twitter.com/numba_jit/status/1790717466915577961

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Tag `v0.44.0dev0` to start new development cycle on `main`. https://github.com/numba/llvmlite/releases/tag/v0.44.0dev0
* [x] <strike>Update release checklist template with any additional bullet points that
      may have arisen during the release.</strike>
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
This release had to be delayed due to a release critical bug in Numba. We expect this to be resolved on Monday and the target date to tag both Numba and llvmlite is now Tuesday 14th may.

**Comment by esc** [comment]
> This release had to be delayed due to a release critical bug in Numba. We expect this to be resolved on Monday and the target date to tag both Numba and llvmlite is now Tuesday 14th may.

https://github.com/numba/numba/pull/9568

**Comment by esc** [comment]
The release process has been resumed.

**Comment by esc** [comment]
it is done.
