### ISSUE TITLE
llvmlite 0.43.0 Checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#1058]
## llvmlite 0.43.0

* [ ] <strike>Cherry-pick items from the 0.43.0 milestone into a PR targeting the release branch.</strike> (no rc bugs)
* [x] Update `CHANGE_LOG` on PR.
  * [x] https://github.com/numba/llvmlite/pull/1059
* [x] Have PR reviewed and merged.
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
  * [x] conda package build and test. `Build llvmlite_287`
  * [x] wheel build `Build llvmlite_wheel_67`
* [x] Annotated tag `v0.43.0` on release branch (`llvmlite` tags DO have a `v` prefix). https://github.com/numba/llvmlite/releases/tag/v0.43.0
* [x] Build and upload conda packages on buildfarm (check "upload"). `llvmlite_288`
* [x] Build wheels and sdist on the buildfarm (check "upload"). `llvmlite_wheel_68`
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`.
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
* [x] Post link to Twitter and Mastodon and anywhere else that is appropriate.

### Post release

* [x] Cherry-pick changes to the `CHANGE_LOG` to `main`. (FINAL ONLY) https://github.com/numba/llvmlite/pull/1060
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] <strike>Update release checklist template with any additional bullet points that
      may have arisen during the release.</strike>
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
it's shipped 🚢
