### ISSUE TITLE
llvmlite 0.44.0rc1 Checklist

### ISSUE THREAD

**Issue by kc611** [numba/llvmlite#1093]
## llvmlite 0.44.0rc1

* [x] Merge to `main`.
    * [x] Remaining Pull-Requests from milestone: https://github.com/numba/llvmlite/milestone/26
* [x] Create 0.44 release branch `release0.44`
    * [x] Update `CHANGE_LOG` in a PR targeting the release branch: https://github.com/numba/llvmlite/pull/1096
    * [x] Follow the format of previous `CHANGE_LOG` entries.
* [x] Get the change-log-PR reviewed and merged.
* [x] merge https://github.com/numba/llvmlite/pull/1099
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
    * [x] conda package build and test. (Run ID: `llvmlite_318`)
    * [x] wheel build. (Run ID: `llvmlite_wheel_72`)
* [x] Test `HEAD` of release branch on conda-forge
* [x] Annotated tag `v0.44.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix). ([v0.44.0rc1 tag](https://github.com/numba/llvmlite/releases/tag/v0.44.0rc1))
* [x] Build and upload conda packages on buildfarm (check "upload"). (Run ID: `llvmlite_319`)
* [x] Build wheels and sdist on the buildfarm (check "upload"). (Run ID: `llvmlite_wheel_73`)
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`. ([Conda files](https://anaconda.org/numba/llvmlite/files?sort=basename&sort_order=desc&version=0.44.0rc1))
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. ([PyPi Link](https://pypi.org/project/llvmlite/0.44.0rc1/))
* [x] Initialize and verify ReadTheDocs build. [RTD Link](https://llvmlite.readthedocs.io/en/v0.44.0rc1/)
* [x] Send RC announcement email / post announcement to discourse group. (https://numba.discourse.group/t/ann-numba-0-61-0rc1-and-llvmlite-0-44-0rc1-are-out/2816)
* [x] Post link to X and Mastodon and anywhere else that is appropriate.

### Post Release:

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Tag 0.44+1.0dev0 to start new development cycle on `main`.
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release. 
  * [x] https://github.com/numba/llvmlite/pull/1112
* [x] Close milestone (and then close this release issue).

**Comment by stuartarchibald** [comment]
I just noticed that the `README.rst` in the root of the project is out of date once 0.44 is tagged, it refers to 0.41 onward needing LLVM 14, this release requires that the statement is updated. Similarly an update to the docs is needed to get the inter-sphinx cross referencing from LLVM 15:
https://github.com/numba/llvmlite/blob/ff09528cecd206bbe50a8a685b4fb34a3e970ebf/docs/source/conf.py#L304

**Comment by esc** [comment]
The checklist must be updated to include a bullet to check and update the compatibility matrix in the README.rst.

**Comment by esc** [comment]
RC2 checklist is here: https://github.com/numba/llvmlite/issues/1109

**Comment by esc** [comment]
> The checklist must be updated to include a bullet to check and update the compatibility matrix in the README.rst.

This is now here: https://github.com/numba/llvmlite/pull/1112
