### ISSUE TITLE
llvmlite 0.44.0rc2 Checklist

### ISSUE THREAD

**Issue by kc611** [numba/llvmlite#1109]
## llvmlite 0.44.0rc2 

* [x] Cherry-pick items from the 0.44.0rc2 milestone into a PR targeting the release branch.
  * [x] https://github.com/numba/llvmlite/pull/1111 
* [x] Have cherry-pick-PR reviewed and merged.
* [x] Make PR for updates to `CHANGE_LOG`
  * [x] https://github.com/numba/llvmlite/pull/1115 
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
  * [x] conda package build and test. (`llvmlite_323`)
  * [x] wheel build. (`llvmlite_wheel_76`)
* [x] Annotated tag `v0.44.0rc2 ` on release branch (`llvmlite` tags DO have a `v` prefix). (https://github.com/numba/llvmlite/releases/tag/v0.44.0rc2)
* [x] Build and upload conda packages on buildfarm (check "upload"). (`llvmlite_324`)
* [x] Build wheels and sdist on the buildfarm (check "upload").  (`llvmlite_wheel_77`)
* [x] Verify packages uploaded to Anaconda Cloud and copy to `numba/label/main`. (https://anaconda.org/numba/llvmlite/files?version=0.44.0rc2)
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`). 
* [x] Verify wheels for all platforms arrived on PyPi. (https://pypi.org/project/llvmlite/0.44.0rc2/#files)
* [x] Verify ReadTheDocs build. (https://app.readthedocs.org/projects/llvmlite/builds/?version__slug=v0.44.0rc2)
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
  * [x] https://numba.discourse.group/t/ann-numba-0-61-0rc2-and-llvmlite-0-44-0rc2-are-out/2845 
* [x] Post link to Twitter and Mastodon and anywhere else that is appropriate.
  * [x] https://x.com/numba_jit/status/1869741054024630767 

### Post release

* [ ] ~~Cherry-pick changes to the `CHANGE_LOG` to `main`. (FINAL ONLY)~~
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] ~~Update release checklist template with any additional bullet points that
      may have arisen during the release.~~
* [ ] ~~Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).~~
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Two PRs in the milestone left that need a review and merge to `main`:

https://github.com/numba/llvmlite/pull/1113
https://github.com/numba/llvmlite/pull/1114

**Comment by esc** [comment]
All done.
