### ISSUE TITLE
llvmlite 0.38.1 checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#840]
## llvmlite 0.38.1
* [x] Backport M1 support patch and target the release branch
  * original at: https://github.com/numba/llvmlite/pull/813
  * backport at: https://github.com/numba/llvmlite/pull/841
* [x] Create PR for changelog modifications
  * https://github.com/numba/llvmlite/pull/842
* [x] Create PR for updating the OSX image on public_ci
  * https://github.com/numba/llvmlite/pull/845 
* [x] Review and merge change log modifications and backport to 0.38 release branch.
* [x] Annotated tag `v0.38.1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [x] Build conda packages on buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * https://anaconda.org/numba/llvmlite/files?version=0.38.1
* [x] Build wheels (`$PYTHON_VERSIONS`) on the buildfarm.
* [x] Upload wheels and sdist to PyPI and verify arrival. (upload from `ci_artifacts`).
  * https://pypi.org/project/llvmlite/0.38.1/
* [x] Verify ReadTheDocs build.
  * https://llvmlite.readthedocs.io/en/v0.38.1/
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
  * https://numba.discourse.group/t/llvmlite-0-38-1/1340 
* [x] Post link to Twitter.
  * https://twitter.com/numba_jit/status/1528705056979263488

### Post release

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Cherry-Pick changelog modifications to `main` via PR
  * https://github.com/numba/llvmlite/pull/846 
* [x] merge checklist templates at: https://github.com/numba/llvmlite/pull/819
* [x] Close milestone (and then close this release issue).
  *  https://github.com/numba/llvmlite/milestone/16

**Comment by esc** [comment]
https://github.com/numba/llvmlite/pull/844 is green and should probably be merged, then the other two PRs can be re-run.

**Comment by esc** [comment]
All PRs for the release merged. We decided to run this through the Anaconda Build Farm before tagging though, to have more confidence in the release.

**Comment by esc** [comment]
Note to selves: the changelog modifications must be cherry-picked to `main`.

**Comment by ngam** [comment]
@esc reporting an issue here, when llvmlite and numba are installed the "regular way":

```
~$ 
~$ python3.10 -m pip install -U numba        
Collecting numba
  Using cached numba-0.55.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... done
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.1-cp310-cp310-macosx_11_0_arm64.whl (23.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 2.0 MB/s eta 0:00:00
Collecting numpy<1.22,>=1.18
  Downloading numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from numba) (58.1.0)
Building wheels for collected packages: numba
  Building wheel for numba (setup.py) ... done
  Created wheel for numba: filename=numba-0.55.1-cp310-cp310-macosx_12_0_universal2.whl size=2445682 sha256=9dff2f8f46f65309493f467236cf05c7d677d55d6483f9d9c24dcc1747caccef
  Stored in directory: /Users/ngam/Library/Caches/pip/wheels/47/e8/65/0038d5154c2d4cd63e295fe0cd939852e1ea340b7c6b97784c
Successfully built numba
Installing collected packages: numpy, llvmlite, numba
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
Successfully installed llvmlite-0.38.1 numba-0.55.1 numpy-1.21.6
~$ python3.10                        
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/core/ir_utils.py", line 16, in <module>
    from numba.core.extending import _Intrinsic
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/core/extending.py", line 19, in <module>
    from numba.core.pythonapi import box, unbox, reflect, NativeValue  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/core/pythonapi.py", line 12, in <module>
    from numba import _helperlib
ImportError: numpy.core.multiarray failed to import
>>> 


```

The fix is to force it to skip the binaries for numba:

```
~$ python3.10 -m pip uninstall numba llvmlite
Found existing installation: numba 0.55.1
Uninstalling numba-0.55.1:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.10/bin/numba
    /Library/Frameworks/Python.framework/Versions/3.10/bin/pycc
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba-0.55.1.dist-info/*
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numba/*
Proceed (Y/n)? y
  Successfully uninstalled numba-0.55.1
Found existing installation: llvmlite 0.38.1
Uninstalling llvmlite-0.38.1:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llvmlite-0.38.1.dist-info/*
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llvmlite/*
Proceed (Y/n)? y
  Successfully uninstalled llvmlite-0.38.1
~$ python3.10 -m pip install -U llvmlite     
Collecting llvmlite
  Using cached llvmlite-0.38.1-cp310-cp310-macosx_11_0_arm64.whl (23.1 MB)
Installing collected packages: llvmlite
Successfully installed llvmlite-0.38.1
~$ python3.10 -m pip install -U --no-binary numba numba
Collecting numba
  Using cached numba-0.55.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from numba) (0.38.1)
Requirement already satisfied: numpy<1.22,>=1.18 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from numba) (1.21.6)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from numba) (58.1.0)
Skipping wheel build for numba, due to binaries being disabled for it.
Installing collected packages: numba
  Running setup.py install for numba ... done
Successfully installed numba-0.55.1
~$ python3.10                                          
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> numba.__version__
'0.55.1'
>>> 
```

**Comment by esc** [comment]
@ngam thank you for reporting this!

I have debugged your issue and  it goes as follows:

There is currently no Numba wheel on PyP, so your `pip` get's the source package instead. It then uses the installed NumPy 1.22 to compile and link Numba from source. Then the Numba version limitation kicks in and installs an older NumPy, 1.21.6, into your environment and removed the 1.22. Then, when you `import numba`, this imports numpy and then numpy complains that numba was compiled against a newer version, which is why you see:

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

The `--no-binary` is a red herring, there are no binaries for M1 on PyPi at present. The only reason it works in your case is because the second time you install Numba from source, the older NumPy 1.21.6 is already installed in the environment, this is used to compile Numba and then Numba works because it is imported in an environment with the same NumPy as it was compiled against.

This is issue will be resolved soon, when then 0.55.2 release is complete and wheels for M1 for Numba become available too. It is not necessary to open a new issue on the tracker for this.

**Comment by ngam** [comment]
> @ngam thank you for reporting this!
> 
> I have debugged your issue and it goes as follows:
> 
> There is currently no Numba wheel on PyPi, so your `pip` get's the source package instead. It then uses the installed NumPy 1.22 to compile and link Numba from source. Then the Numba version limitation kicks in and installs an older NumPy, 1.21.6, into your environment and removes the 1.22. Then, when you `import numba`, this imports NumPy and then NumPy complains that Numba was compiled against a newer version of NumPy, which is why you see:
> 
> ```
> RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
> ```
> 
> The `--no-binary` is a red herring, there are no binaries for M1 on PyPi at present. The only reason it works in your case is because the second time you install Numba from source, the older NumPy 1.21.6 is already installed in the environment, this is used to compile Numba and then Numba works because it is imported in an environment with the same NumPy as it was compiled against.
> 

I am 99% certain your explanation is wrong because I played around with the numpy versions --- it complains more straightforwardly about numpy compatibility if the version is wrong. I think the issue here is this weird wheel

```
Created wheel for numba: filename=numba-0.55.1-cp310-cp310-macosx_12_0_universal2.whl
```

which the `--no-binary` flag disables creating. Thus, I would assume there is something weird going on in this "universal2" wheel building... but I have no idea what's going on, so my 99% certainty should be taken with a tablespoon of salt 😅  

> This is issue will be resolved soon, when then 0.55.2 release is complete and wheels for M1 for Numba become available too. It is not necessary to open a new issue on the tracker for this.

Yes, that's why I am reporting this to help flag this issue in case it causes delays in the upcoming releases. I would like to explore using numba in the near future, and so I am keeping eyes on the project.

At any rate, the numpy thing caused problems for other libraries for me, and so I reverted back to your experimental dev wheels on anaconda.org for now. I assume the numpy strictness (<1.22) is also resolved

**Comment by ngam** [comment]
> @ngam thank you for reporting this!
> 
> I have debugged your issue and it goes as follows:
> 
> There is currently no Numba wheel on PyPi, so your `pip` get's the source package instead. It then uses the installed NumPy 1.22 to compile and link Numba from source. Then the Numba version limitation kicks in and installs an older NumPy, 1.21.6, into your environment and removes the 1.22. Then, when you `import numba`, this imports NumPy and then NumPy complains that Numba was compiled against a newer version of NumPy, which is why you see:
> 
> ```
> RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
> ```
> 
> The `--no-binary` is a red herring, there are no binaries for M1 on PyPi at present. The only reason it works in your case is because the second time you install Numba from source, the older NumPy 1.21.6 is already installed in the environment, this is used to compile Numba and then Numba works because it is imported in an environment with the same NumPy as it was compiled against.
> 
> This is issue will be resolved soon, when then 0.55.2 release is complete and wheels for M1 for Numba become available too. It is not necessary to open a new issue on the tracker for this.

Prematurely misread your comment earlier and I had to delete a hasty comment. Thanks for the prompt response! My intention is to help flag issues as I would like to use numba soon

**Comment by esc** [comment]
> Prematurely misread your comment earlier and I had to delete a hasty comment. Thanks for the prompt response! My intention is to help flag issues as I would like to use numba soon

You can track the progress of the 0.55.2 release here: https://github.com/numba/numba/issues/8066

**Comment by esc** [comment]
This is now done.
