### ISSUE TITLE
llvmlite 0.39.0rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#859]
## llvmlite 0.39.0

* [x] Merge change log changes.
    - [x] "[PR with changelog entries".](https://github.com/numba/llvmlite/pull/858)
* [x] Create 0.39 release branch `release0.39`
  - https://github.com/numba/llvmlite/tree/release0.39 
* [x] Annotated tag `v0.39.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix).
  - https://github.com/numba/llvmlite/releases/tag/v0.39.0rc1
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  - https://anaconda.org/numba/llvmlite/files?version=0.39.0rc1&type=conda
* [x] Upload wheels and sdist to <strike>PyPI.</strike> anaconda.org (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on <strike>PyPi</strike> anaconda.org using the `numba/label/wheels`.
  - https://anaconda.org/numba/llvmlite/files?version=0.39.0rc1&type=pypi
* [x] Initialize and verify ReadTheDocs build.
  - https://llvmlite.readthedocs.io/en/v0.39.0rc1/
* [x] Send RC announcement email / post announcement to discourse group.
  - https://numba.discourse.group/t/ann-llvmlite-0-39-0-rc1/1414
* [x] Post link to Twitter.
  - https://twitter.com/numba_jit/status/1541729168462856192

### Post Release:

* [x] Clean up `ci_artifacts`.
* [x] Tag 0.40.0dev0 to start new development cycle on `main`.
  - https://github.com/numba/llvmlite/releases/tag/v0.40.0dev0
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * [x] Tag command is missing `rc1` suffix
  * [x] https://github.com/numba/llvmlite/pull/860
* [ ] Close milestone (and then close this release issue).

**Comment by esc** [comment]
> [pypa/pypi-support#2039](https://github.com/pypa/pypi-support/issues/2039)

The limit on PyPi has been increased 20GB, but since the 0.39.0rc1 release was deleted from PyPi we can't upload a new distribution with that name. The RC1 will only appear on anaconda.org as a result.

**Comment by esc** [comment]
It's a wrap! 📦
