### ISSUE TITLE
llvmlite 0.39.0 Checklist

### ISSUE THREAD

**Issue by sklam** [numba/llvmlite#861]
## llvmlite 0.39.0

* [x] Cherry-pick items from the 0.39.0 milestone into a PR. (none)
* [x] Approve change log modifications and cherry-pick. https://github.com/numba/llvmlite/pull/863
* [x] Update release date for 0.39.0 https://github.com/numba/llvmlite/blob/1d1b49b59fb46d3c23eb2386b01a74783318f23e/CHANGE_LOG#L1
* [x] Merge change log modifications and cherry-picks to X.Y release branch.
  * [x] https://github.com/numba/llvmlite/pull/866
* [x] Annotated tag `v0.39.0` on release branch (`llvmlite` tags DO have a `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * https://anaconda.org/numba/llvmlite/files?version=0.39.0
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
  * https://pypi.org/project/llvmlite/#files 
* [x] Verify wheels for all platforms arrived on PyPi.
* [x] Verify ReadTheDocs build.
  * https://llvmlite.readthedocs.io/en/v0.39.0/ 
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
  * https://numba.discourse.group/t/ann-llvmlite-0-39-0/1460 
* [x] Post link to Twitter.
  * https://twitter.com/numba_jit/status/1551874375506329600 

### Post release

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template.
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [ ] <strike> Close milestone (and then close this release issue). </strike>

**Comment by esc** [comment]
No milestone for this one.
