### ISSUE TITLE
llvmlite 0.39.1 Checklist

### ISSUE THREAD

**Issue by apmasell** [numba/llvmlite#877]
## llvmlite 0.39.1

* [X] Cherry-pick items from the 0.39.1 milestone into a PR. (https://github.com/numba/llvmlite/pull/875)
* [x] Approve change log modifications and cherry-pick. (https://github.com/numba/llvmlite/pull/878)
* [x] Merge change log modifications and cherry-picks to 0.39 release branch.
* [x] Annotated tag `v0.39.1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [x] Build and upload conda packages on buildfarm (check "upload").
* [x] Build wheels and sdist on the buildfarm (check "upload").
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`. (https://anaconda.org/numba/llvmlite/files?version=0.39.1)
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi. (https://pypi.org/project/llvmlite/0.39.1/#files)
* [x] Verify ReadTheDocs build. (https://llvmlite.readthedocs.io/en/v0.39.1/)
* [x] Send RC/FINAL announcement email / post announcement to discourse group. (https://numba.discourse.group/t/ann-numba-0-56-2-llvmlite-0-39-1/1542)
* [x] Post link to Twitter. (https://twitter.com/numba_jit/status/1565702324294746115)

### Post release

* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] ~~Update release checklist template.~~
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
That's all folks.
