### ISSUE TITLE
llvmlite 0.40.0rc1 Checklist

### ISSUE THREAD

**Issue by stuartarchibald** [numba/llvmlite#929]
## llvmlite 0.40.0

* [ ] Merge to `main`.
    - [ ] "remaining Pull-Requests from milestone".
* [ ] Merge change log changes.
    - [ ] "PR with changelog entries".
* [ ] Create 0.40 release branch `release0.40`
* [ ] Annotated tag `v0.40.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [ ] Build and upload conda packages on buildfarm (check "upload").
* [ ] Build wheels and sdist on the buildfarm (check "upload").
* [ ] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
* [ ] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [ ] Verify wheels for all platforms arrived on PyPi.
* [ ] Initialize and verify ReadTheDocs build.
* [ ] Send RC announcement email / post announcement to discourse group.
* [ ] Post link to Twitter.

### Post Release:

* [ ] Clean up `ci_artifacts`.
* [ ] Tag 0.41.0dev0 to start new development cycle on `main`.
* [ ] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [ ] Close milestone (and then close this release issue).

**Comment by sklam** [comment]
There are two set of wheels uploaded for non-linux platform because the first set (no build number) incorrectly linked to llvmdev=11. The second set fixed this issue and bumped the build number to 1. Again, this only affected non-linux wheels.
