### ISSUE TITLE
llvmlite v0.40.1-rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#955]
## llvmlite v0.40.1-rc1

* [ ] Cherry-pick items from the v0.40.1-rc1 milestone into a PR.
* [ ] Approve change log modifications and cherry-pick.
* [ ] Merge change log modifications and cherry-picks to 0.40 release branch.
  * [ ] https://github.com/numba/numba/pull/XXXX
* [ ] Annotated tag `v0.40.1-rc1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [ ] Build and upload conda packages on buildfarm (check "upload").
* [ ] Build wheels and sdist on the buildfarm (check "upload").
* [ ] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
* [ ] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [ ] Verify wheels for all platforms arrived on PyPi.
* [ ] Verify ReadTheDocs build.
* [ ] Send RC/FINAL announcement email / post announcement to discourse group.
* [ ] Post link to Twitter.

### Post release

* [ ] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] Update release checklist template.
* [ ] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [ ] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Notes for changes required for the checklist:

* Add bullet to test before tagging
* Add bullet to cherry-pick changelog onto `main` when done
* Add bullet to post to mastodon and everyone social (Anaconda internal)

**Comment by esc** [comment]
checklist updates are here: https://github.com/numba/llvmlite/pull/960

**Comment by esc** [comment]
That's all.
