### ISSUE TITLE
llvmlite 0.41.0-rc1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#977]
## llvmlite 0.41.0

* [ ] Merge to `main`.
    * [ ] "remaining Pull-Requests from milestone".
* [ ] Create `0.41` release branch `release0.41`
    * [ ] Update `CHANGE_LOG` in a PR targeting the release branch.
* [ ] Get the change-log-PR reviewed and merged.
* [ ] Test `HEAD` of release branch on buildfarm (pre-tag testing):
    * [ ] conda package build and test.
    * [ ] wheel build.
* [ ] Annotated tag `v0.41.0rc1` on release branch (`llvmlite` tags DO have a `v` prefix).
* [ ] Build and upload conda packages on buildfarm (check "upload").
* [ ] Build wheels and sdist on the buildfarm (check "upload").
* [ ] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
* [ ] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [ ] Verify wheels for all platforms arrived on PyPi.
* [ ] Initialize and verify ReadTheDocs build.
* [ ] Send RC announcement email / post announcement to discourse group.
* [ ] Post link to Twitter and Mastodon and anywhere else that is appropriate.

### Post Release:

* [ ] Cherry-pick changes to the `CHANGE_LOG` to `main`
* [ ] Clean up `ci_artifacts` by moving files to subdirectories
* [ ] Tag 0.42.0dev0 to start new development cycle on `main`.
* [ ] Update release checklist template with any additional bullet points that
      may have arisen during the release.
* [ ] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Note to self for the final: release notes need an introduction and mention that this is the last version to support the `win32` platform for conda packages and wheels.

**Comment by esc** [comment]
Note to self: twitter is now called X

**Comment by esc** [comment]
@kc611 I have created to https://github.com/numba/llvmlite/pull/985 -- merging it to `main` will enable completion of the RC.

**Comment by esc** [comment]
llvmlite is a wrap
