### ISSUE TITLE
llvmlite 0.41.1 Checklist

### ISSUE THREAD

**Issue by esc** [numba/llvmlite#999]
## llvmlite 0.41.1

* [x] Cherry-pick items from the 0.41.1 milestone into a PR targeting the release branch.
* [x] Update `CHANGE_LOG` on cherry-pick-PR.
* [x] Have cherry-pick-PR reviewed and merged.
  * [x] https://github.com/numba/llvmlite/pull/1004
* [x] Test `HEAD` of release branch on buildfarm (pre-tag testing):
  * [x] conda package build and test. (`llvmlite_247`)
  * [x] wheel build. (`llvmlite_wheel_54`)
* [x] Annotated tag `v0.41.1` on release branch (`llvmlite` tags DO have a `v` prefix).
  * [x] https://github.com/numba/llvmlite/releases/tag/v0.41.1
* [x] Build and upload conda packages on buildfarm (check "upload").
  * [x] `llvmlite_248` 
* [x] Build wheels and sdist on the buildfarm (check "upload").
  * [x] `llvmlite_wheel_55` 
* [x] Verify packages uploaded to Anaconda Cloud and move to `numba/label/main`.
  * [x] https://anaconda.org/numba/llvmlite/files?sort=basename&version=0.41.1&sort_order=desc
* [x] Upload wheels and sdist to PyPI. (upload from `ci_artifacts`).
* [x] Verify wheels for all platforms arrived on PyPi.
  * [x] https://pypi.org/project/llvmlite/0.41.1/#files 
* [x] Verify ReadTheDocs build.
  * [x] https://llvmlite.readthedocs.io/en/v0.41.1/ 
* [x] Send RC/FINAL announcement email / post announcement to discourse group.
  * [x] https://numba.discourse.group/t/ann-numba-0-58-1-and-llvmlite-0-41-1/2219 
* [x] Post link to Twitter and Mastodon and anywhere else that is appropriate.
  * [x] https://twitter.com/numba_jit/status/1714647834329276674 

### Post release

* [x] Cherry-pick changes to the `CHANGE_LOG` to `main`. (FINAL ONLY)
  * [x] https://github.com/numba/llvmlite/pull/1006
* [x] Clean up `ci_artifacts` by moving files to subdirectories
* [x] Update release checklist template with any additional bullet points that
      may have arisen during the release.
  * [x] https://github.com/numba/llvmlite/pull/1007
* [x] Ping Anaconda Distro team to trigger a build for `defaults` (FINAL ONLY).
* [x] Close milestone (and then close this release issue).

**Comment by esc** [comment]
Instead of:

```
Verify packages uploaded to Anaconda Cloud and move to numba/label/main.
```

It should say:

```
Verify packages uploaded to Anaconda Cloud and move to numba/label/main.
```

**Comment by esc** [comment]
It's a wrap!
